aliases: []
creation_timestamp: 1730673169659
current_stage: None
description: null
last_updated_timestamp: 1730673169659
name: Best Model
run_id: 090fb2994eab4635949c8d87f1c6bbe9
run_link: null
source: file:D:/MLpipeline/MLFLOW_TRACKING_URI/0/090fb2994eab4635949c8d87f1c6bbe9/artifacts/model
status: READY
status_message: null
storage_location: file:D:/MLpipeline/MLFLOW_TRACKING_URI/0/090fb2994eab4635949c8d87f1c6bbe9/artifacts/model
user_id: null
version: 2
