artifact_uri: file:D:/MLpipeline/MLFLOW_TRACKING_URI/0/090fb2994eab4635949c8d87f1c6bbe9/artifacts
end_time: 1730673169712
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 090fb2994eab4635949c8d87f1c6bbe9
run_name: judicious-crow-845
run_uuid: 090fb2994eab4635949c8d87f1c6bbe9
source_name: ''
source_type: 4
source_version: ''
start_time: 1730673134724
status: 3
tags: []
user_id: ganeshmahadev2463
